# Generated by Django 5.0.6 on 2024-07-02 10:43

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worckSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgWorck', models.ImageField(upload_to='media/worck/', verbose_name='Главное изображение')),
                ('titleWorck', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('exeptWorck', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('clientWorck', models.CharField(blank=True, max_length=500, verbose_name='Клиент')),
                ('dateWorck', models.DateField(default=datetime.date.today, verbose_name='Дата стартра работы')),
                ('date_old_Worck', models.DateField(default=datetime.date.today, verbose_name='Дата окончания работы')),
                ('linkWorck', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('desk_title_Worck', models.CharField(max_length=500, verbose_name='Заголовок блока описания')),
                ('contentWorck', ckeditor.fields.RichTextField(verbose_name='Контент работы')),
                ('storyWorck', models.TextField(blank=True, verbose_name='История работы')),
                ('approachWorck', models.TextField(blank=True, verbose_name='Описание что было сделано')),
            ],
        ),
    ]
