# Generated by Django 5.0.6 on 2024-07-02 10:51

import datetime
import django.db.models.deletion
import worck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worcksite',
            name='dateWorck',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата старта работы'),
        ),
        migrations.CreateModel(
            name='galleryWorck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img_Worck', models.ImageField(upload_to=worck.models.upload_gallery_to, verbose_name='Добавить фото')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='worck.worcksite', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
            },
        ),
    ]
