# Generated by Django 5.0.6 on 2024-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worck', '0002_alter_worcksite_dateworck_galleryworck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worcksite',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.RemoveField(
            model_name='galleryworck',
            name='service',
        ),
        migrations.AddField(
            model_name='worcksite',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='works', to='worck.galleryworck'),
        ),
    ]
