# Generated by Django 5.0.6 on 2024-07-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worck', '0003_alter_worcksite_options_remove_galleryworck_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worcksite',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='related_works', to='worck.galleryworck'),
        ),
    ]
