# Generated by Django 5.0.6 on 2024-07-02 13:00

import worck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worck', '0005_alter_worcksite_imgworck'),
    ]

    operations = [
        migrations.AddField(
            model_name='worcksite',
            name='imgWorck_large',
            field=models.ImageField(blank=True, null=True, upload_to=worck.models.upload_gallery_to, verbose_name='Большое изображение'),
        ),
    ]
