# Generated by Django 5.0.6 on 2024-07-02 13:03

import worck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worck', '0006_worcksite_imgworck_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='worcksite',
            name='imgWorck_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=worck.models.upload_worck_to, verbose_name='Миниатюра изображения'),
        ),
        migrations.AlterField(
            model_name='worcksite',
            name='imgWorck',
            field=models.ImageField(upload_to=worck.models.upload_worck_to, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='worcksite',
            name='imgWorck_large',
            field=models.ImageField(blank=True, null=True, upload_to=worck.models.upload_worck_to, verbose_name='Большое изображение'),
        ),
    ]
