# Generated by Django 5.0.6 on 2024-07-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worck', '0007_worcksite_imgworck_thumb_alter_worcksite_imgworck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worcksite',
            name='imgWorck',
        ),
    ]
