# Generated by Django 5.0.6 on 2024-07-02 15:51

import worck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worck', '0008_remove_worcksite_imgworck'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryWorck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleCategory', models.CharField(max_length=500, verbose_name='Название категории')),
                ('slugCategory', models.CharField(max_length=500, verbose_name='Ссылка на категорию')),
            ],
        ),
        migrations.AlterField(
            model_name='worcksite',
            name='imgWorck_large',
            field=models.ImageField(default=111, upload_to=worck.models.upload_worck_to, verbose_name='Большое изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worcksite',
            name='imgWorck_thumb',
            field=models.ImageField(default=123, upload_to=worck.models.upload_worck_to, verbose_name='Миниатюра изображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worcksite',
            name='categoryWorckInfo',
            field=models.ManyToManyField(blank=True, to='worck.categoryworck', verbose_name='Категория для работы'),
        ),
    ]
