# Generated by Django 5.0.6 on 2024-07-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worck', '0009_categoryworck_alter_worcksite_imgworck_large_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryworck',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
