# Generated by Django 5.0.6 on 2024-07-05 07:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleGallery', models.CharField(max_length=500, verbose_name='Название страницы с фотографиями')),
                ('slugGallery', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Заполняется автоматически')),
                ('exeptGallery', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('contentGallery', ckeditor.fields.RichTextField(verbose_name='Контент новости')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photos')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.gallerysite')),
            ],
        ),
    ]
