# Generated by Django 5.0.6 on 2024-07-05 08:13

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysite',
            name='dataGallery',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата поездки'),
        ),
        migrations.AlterField(
            model_name='gallerysite',
            name='contentGallery',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент для галереи'),
        ),
    ]
