# Generated by Django 5.0.6 on 2024-07-02 09:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicesSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleServices', models.CharField(max_length=500, verbose_name='Название направления')),
                ('exeptServices', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('contentServices', ckeditor.fields.RichTextField(verbose_name='Контент услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
