# Generated by Django 5.0.6 on 2024-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessite',
            name='imgServices',
            field=models.ImageField(default=123, upload_to='media/services/', verbose_name='Главное изображение'),
            preserve_default=False,
        ),
    ]
