# Generated by Django 5.0.6 on 2024-07-10 12:27

import settings.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSontact', models.CharField(max_length=500, verbose_name='Название пункта с контактами')),
                ('titleSontact', models.CharField(max_length=500, verbose_name='Номер телефона/почта/адрес')),
                ('linkSontact', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('imgSontact', models.CharField(help_text='Ссылка на шрифтовой пак https://fontawesome.ru/', max_length=500, verbose_name='Класс по каторому будет показана иконка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='experienceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearExperience', models.CharField(max_length=500, verbose_name='Год начала карьеры')),
                ('year_old_Experience', models.CharField(blank=True, max_length=500, null=True, verbose_name='Год окончания карьеры')),
                ('postExperience', models.CharField(max_length=500, verbose_name='Название должности')),
                ('companyExperience', models.CharField(max_length=500, verbose_name='Компания')),
                ('textExperience', models.CharField(max_length=500, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='FormsHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMIN_EMAIL', models.EmailField(default='bearcoderr@gmail.com', max_length=254)),
                ('nameFormsHome', models.CharField(max_length=200, verbose_name='Имя отправителя')),
                ('emailFormsHome', models.EmailField(max_length=254, verbose_name='Email отправителя')),
                ('callFormsHome', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=10)),
                ('massageFormsHome', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MenuSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLink', models.TextField(default='#', verbose_name='Название ссылки в меню')),
                ('link', models.TextField(default='#', verbose_name='Ссылка на блок на сайте')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='numberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberTitle', models.CharField(max_length=500, verbose_name='Впишите число или текст')),
                ('numberText', models.CharField(max_length=500, verbose_name='Напишите текст')),
                ('numberDopSimvol', models.CharField(max_length=500, verbose_name='Доп символ после цифры')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='skillsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleSkills', models.CharField(max_length=500, verbose_name='Название')),
                ('countSkills', models.PositiveIntegerField(verbose_name='Проценты')),
                ('imgSkills', settings.fields.SVGImageField(upload_to='photos/home/skill/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='socialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altSocial', models.CharField(max_length=500, verbose_name='Название соц. сети')),
                ('lincSocial', models.URLField(max_length=1000)),
                ('classSocial', models.CharField(help_text='Ссылка на шрифтовой пак https://fontawesome.ru/', max_length=500, verbose_name='Класс по каторому будет показана иконка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgHome', models.ImageField(upload_to='media/photos/home/', verbose_name='Главное изображение')),
                ('logoSite', models.ImageField(upload_to='media/photos/', verbose_name='Логотип сайта')),
                ('favSite', models.ImageField(upload_to='media/photos/', verbose_name='Фавикон сайта')),
                ('titleHome', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('buttonHeader', models.CharField(max_length=500, verbose_name='Название кнопки')),
                ('sub_titleHome', models.CharField(max_length=500, verbose_name='Подзаголовок')),
                ('textHome', models.TextField(default='Привет', verbose_name='Подзаголовок')),
                ('copyText', models.CharField(max_length=500, verbose_name='Текст копирайта')),
                ('MenuSiteList', models.ManyToManyField(blank=True, to='settings.menusite', verbose_name='Меню')),
                ('contactHome', models.ManyToManyField(blank=True, to='settings.contactsettings', verbose_name='Контакты')),
                ('experienceHome', models.ManyToManyField(blank=True, to='settings.experiencesettings', verbose_name='Вакансия')),
                ('numberlHome', models.ManyToManyField(blank=True, to='settings.numbersettings', verbose_name='Номер на главной страницы')),
                ('skillsHome', models.ManyToManyField(blank=True, to='settings.skillssettings', verbose_name='Skill')),
                ('socialHome', models.ManyToManyField(blank=True, to='settings.socialsettings', verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
    ]
