# Generated by Django 5.0.6 on 2024-07-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formshome',
            old_name='ADMIN_EMAIL',
            new_name='admin_email',
        ),
    ]
