# Generated by Django 5.0.6 on 2024-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_admin_email_formshome_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formshome',
            name='admin_email',
        ),
        migrations.AddField(
            model_name='settings',
            name='admin_email',
            field=models.EmailField(default='bearcoderr@gmail.com', max_length=254),
        ),
    ]
