# Generated by Django 5.0.6 on 2024-07-10 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_formshome_admin_email_settings_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formshome',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
