# Generated by Django 5.0.6 on 2024-07-10 11:55

import ckeditor.fields
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameComm', models.CharField(max_length=500, verbose_name='Имя')),
                ('emailComm', models.EmailField(max_length=500, verbose_name='Email')),
                ('textComm', models.TextField(verbose_name='Сообщение')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата публиации')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'app_feedback',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='galleryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgNews', models.ImageField(upload_to='photos/news/', verbose_name='Главное изображение записи')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='newsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleCategory', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slagCategory', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на категорию')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='newsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleTag', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slagTag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgNews', models.ImageField(upload_to='photos/news/', verbose_name='Главное изображение записи')),
                ('dataNews', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публиации')),
                ('titleNews', models.CharField(max_length=500, verbose_name='Название статьи')),
                ('slugNews', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Заполняется автоматически')),
                ('contentNews', ckeditor.fields.RichTextField(verbose_name='Контент новости')),
                ('feetbicke', models.ManyToManyField(blank=True, to='News.formsnews', verbose_name='Отзыв')),
                ('gallery', models.ManyToManyField(blank=True, to='News.gallerynews', verbose_name='Галерея фотографий')),
                ('category', models.ManyToManyField(blank=True, to='News.newscategory', verbose_name='Категории статьи')),
                ('tags', models.ManyToManyField(blank=True, to='News.newstag', verbose_name='Теги статьи')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
