# Generated by Django 5.0.6 on 2024-07-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsnews',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelTable(
            name='formsnews',
            table=None,
        ),
    ]
